#!/usr/bin/env bash
set -e

[ -n "$KEY_DIR" ] || KEY_DIR="$HOME/.keys"

KEY_NAME="$1"
[ -n "$KEY_NAME" ] || {
  echo "usage: decrypt <key-name>" >&2
  exit 1
}

KEY_FILE="${KEY_DIR%/}/$KEY_NAME"
[ -f "$KEY_FILE" ] || {
  echo "decrypt: key file not found: $KEY_FILE" >&2
  exit 2
}

ENCRYPTED_FILE="$2"
[ -n "$ENCRYPTED_FILE" ] || {
  echo "usage: decrypt <key-name> <encrypted-file>" >&2
  exit 3
}

[ -f "$ENCRYPTED_FILE" ] || {
  echo "decrypt: encrypted file not found: $ENCRYPTED_FILE" >&2
  exit 4
}

bzip2 -dc "$ENCRYPTED_FILE" | openssl aes-256-cbc -d -a -pass file:"$KEY_FILE" | bzip2 -d