#!/usr/bin/env bash
set -e

[ -n "$KEY_DIR" ] || KEY_DIR="$HOME/.keys"

KEY_NAME="$1"
[ -n "$KEY_NAME" ] || {
  echo "usage: encrypt <key-name>" >&2
  exit 1
}

SNAPSHOT="$2"
[ -n "$SNAPSHOT" ] || {
  echo "usage: encrypt <key-name> <snapshot>" >&2
  exit 2
}

KEY_FILE="${KEY_DIR%/}/$KEY_NAME"
[ -f "$KEY_FILE" ] || {
  echo "encrypt: key file not found: $KEY_FILE" >&2
  exit 3
}

echo "key: $KEY_NAME"
echo "key file: $KEY_FILE"
echo "snapshot: $SNAPSHOT"

zfs send "$SNAPSHOT" | pbzip2 -9 | openssl aes-256-cbc -a -salt -pass file:"$KEY_FILE" | pbzip2 -9